
package com.flightstats.alerts.api.v1;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "FlightAlertsV1SoapService", targetNamespace = "http://v1.api.alerts.flightstats.com/", wsdlLocation = "https://api.flightstats.com/flex/alerts/docs/v1/lts/soap/flightAlertsService.wsdl")
public class FlightAlertsV1SoapService
        extends Service {

    private final static URL FLIGHTALERTSV1SOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException FLIGHTALERTSV1SOAPSERVICE_EXCEPTION;
    private final static QName FLIGHTALERTSV1SOAPSERVICE_QNAME = new QName("http://v1.api.alerts.flightstats.com/", "FlightAlertsV1SoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api.flightstats.com/flex/alerts/docs/v1/lts/soap/flightAlertsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FLIGHTALERTSV1SOAPSERVICE_WSDL_LOCATION = url;
        FLIGHTALERTSV1SOAPSERVICE_EXCEPTION = e;
    }

    public FlightAlertsV1SoapService() {
        super(__getWsdlLocation(), FLIGHTALERTSV1SOAPSERVICE_QNAME);
    }

    public FlightAlertsV1SoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FLIGHTALERTSV1SOAPSERVICE_QNAME, features);
    }

    public FlightAlertsV1SoapService(URL wsdlLocation) {
        super(wsdlLocation, FLIGHTALERTSV1SOAPSERVICE_QNAME);
    }

    public FlightAlertsV1SoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FLIGHTALERTSV1SOAPSERVICE_QNAME, features);
    }

    public FlightAlertsV1SoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FlightAlertsV1SoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (FLIGHTALERTSV1SOAPSERVICE_EXCEPTION != null) {
            throw FLIGHTALERTSV1SOAPSERVICE_EXCEPTION;
        }
        return FLIGHTALERTSV1SOAPSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns FlightAlertsService
     */
    @WebEndpoint(name = "flightAlertsServicePort")
    public FlightAlertsService getFlightAlertsServicePort() {
        return super.getPort(new QName("http://v1.api.alerts.flightstats.com/", "flightAlertsServicePort"), FlightAlertsService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns FlightAlertsService
     */
    @WebEndpoint(name = "flightAlertsServicePort")
    public FlightAlertsService getFlightAlertsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://v1.api.alerts.flightstats.com/", "flightAlertsServicePort"), FlightAlertsService.class, features);
    }

}
